apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: myra-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine    # docker image
          ports:
            - containerPort: 6379   # port the container listens on