name: fintech CI pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test the pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Pipeline is running!"

      - name: List project files
        run: ls

      - name: Setup python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.11"

      - name: Install Install dependencies (ingestion)
        run: pip install -r ingestion/requirements.txt

      - name: Install dependencies (processing)
        run: pip install -r processing/requirements.txt

      - name: Install dependencies (validation)
        run: pip install -r validation/requirements.txt

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build -t ingestion ./ingestion
          docker build -t processing ./processing
          docker build -t validation ./validation

      - name: Start images
        run: docker compose up -d

      - name: Check running containers
        run: docker ps -a

      - name: Wait for ingestion up
        shell: bash
        run: |
          for i in {1..15}; do
            if curl -sf http://localhost:8000/health; then
              echo "Ingestion is up"
              break
            fi
            sleep 3
          done

      - name: Send a transaction
        run: |
          curl -sf -X POST http://localhost:8000/transaction \
          -H "Content-Type: application/json" \
          -d '{"amount": 1000, "currency": "NGN", "sender": "ci_test", "receiver": "merchant_01"}'
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # only deploy on main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2


      - name: Build images
        run: |
          docker build -t ingestion ./ingestion
          docker build -t processing ./processing
          docker build -t validation ./validation

      - name: Push images to ECR
        run: |
          chmod +x scripts/push-to-ecr.sh
          ./scripts/push-to-ecr.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}"

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy

      - name: Tear down
        if: always()
        run: docker compose down -v